disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - force_cast
  - function_body_length

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# parameterized rules can be customized from this configuration file
line_length: 200

# parameterized rules are first parameterized as a warning level, then error level.
type_body_length:
  - 300 # warning
  - 400 # error

variable_name:
  min_length: 2

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
